---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on centos
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution = "CentosOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install ntp agent on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        # update_cache: yes (If you are going to fact with a issue, please uncomment this line)
      when: ansible_distribution = "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start service on centos
      service:
        name: chronyd
        state: started
        enable: yes
      when: ansible_distribution = "CentosOS"

    - name: Start service on ubuntu
      service:
        name: ntp
        state: started
        enable: yes
      when: ansible_distribution = "Ubuntu"

    - name: Banner file
      copy:
        content: "# This server is managed by ansible. No manual changes please."
        dest: /etc/motd

    - name: Deploy ntp agent conf on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"

    - name: Deploy ntp agent conf on ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/nfp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"

    - name: Restart service on centos
      service:
        name: chronyd
        state: restarted
        enable: yes
      when: ansible_distribution = "CentosOS"

    - name: Restart service on ubuntu
      service:
        name: ntp
        state: restarted
        enable: yes
      when: ansible_distribution = "Ubuntu"

    - name: Create folder
      file:
        path: /opt/test21
        state: directory
